ARDUINO_DIR = /usr/share/arduino
ARDMK_DIR = /usr
AVR_TOOLS_DIR = /usr

BOARD_TAG    = mega2560
ARDUINO_PORT = /dev/ttyACM0
MONITOR_PORT = /dev/cu.usb*
ARDUINO_LIBS = 

include /usr/share/arduino/Arduino.mk
